/*
 * generated by Xtext 2.20.0
 */
package org.emoflon.cep.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GrapelUiModule extends AbstractGrapelUiModule {

	public GrapelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
