/*
 * generated by Xtext 2.20.0
 */
package org.emoflon.cep;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GrapelStandaloneSetup extends GrapelStandaloneSetupGenerated {

	public static void doSetup() {
		new GrapelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
