/*
 * generated by Xtext 2.20.0
 */
package org.emoflon.cep.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.emoflon.cep.GrapelRuntimeModule;
import org.emoflon.cep.GrapelStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GrapelIdeSetup extends GrapelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GrapelRuntimeModule(), new GrapelIdeModule()));
	}
	
}
